### ISSUE TITLE
Off-topic: Syntax highlighting for typescript enbedded in yaml

### ISSUE THREAD

**Issue by gentledepp** [brandonkal/vscode-yaml-embed#1]
Hi!

I am trying to figure out how I can add syntax highlighting for typescript/javascript expressions within a yaml file.
Originally, I thought I would have to implement all the grammars (for typescript and yaml) myself.
However, looking at your repo, it seems that you can tie together existing grammars.

If so, could you please get me started by providing links and hints?

I went through the official vs-code extensions tutorials/documentation but couldn't figure out how to do this.

Ideally, I would like to specify fields that either have a scalar value or a script attached:

```yaml
firstName: James
lastName: Bond
agentNumber: 007
displayText: !typescript firstName + ' ' + lastName + ', ' + padLeft(agentNumber, 3,"0")

```

so display uses the properties of its parent field to generate some display text "James Bond, 007"

Obviously, it would also be nice to be able to define reusable functions within the yaml file like so (just an example... I am only playing around with those thoughts)

```yaml
functions
  - padLeft: !typescript | #using the | character to indicate multi-line text (i guess?)
      (input: string, count: number, symbol: string) => {
        // magically prepend the symbol to the input to get a total string length of 'count'
     }
``` 

Any hints would be greatly appreciated!
